# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import service_pb2 as service__pb2


class SocialNetworkStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetPost = channel.unary_unary(
                '/socialnetwork.SocialNetwork/GetPost',
                request_serializer=service__pb2.GetPostRequest.SerializeToString,
                response_deserializer=service__pb2.GetPostResponse.FromString,
                )
        self.CreateComment = channel.unary_unary(
                '/socialnetwork.SocialNetwork/CreateComment',
                request_serializer=service__pb2.CreateCommentRequest.SerializeToString,
                response_deserializer=service__pb2.CreateCommentResponse.FromString,
                )
        self.GetComments = channel.unary_unary(
                '/socialnetwork.SocialNetwork/GetComments',
                request_serializer=service__pb2.GetCommentsRequest.SerializeToString,
                response_deserializer=service__pb2.GetCommentsResponse.FromString,
                )
        self.RegisterClient = channel.unary_unary(
                '/socialnetwork.SocialNetwork/RegisterClient',
                request_serializer=service__pb2.RegisterClientRequest.SerializeToString,
                response_deserializer=service__pb2.RegisterClientResponse.FromString,
                )
        self.GetPromocode = channel.unary_unary(
                '/socialnetwork.SocialNetwork/GetPromocode',
                request_serializer=service__pb2.GetPromocodeRequest.SerializeToString,
                response_deserializer=service__pb2.GetPromocodeResponse.FromString,
                )
        self.ClickPromocode = channel.unary_unary(
                '/socialnetwork.SocialNetwork/ClickPromocode',
                request_serializer=service__pb2.ClickPromocodeRequest.SerializeToString,
                response_deserializer=service__pb2.ClickPromocodeResponse.FromString,
                )
        self.CreatePromocodeComment = channel.unary_unary(
                '/socialnetwork.SocialNetwork/CreatePromocodeComment',
                request_serializer=service__pb2.CreatePromocodeCommentRequest.SerializeToString,
                response_deserializer=service__pb2.CreatePromocodeCommentResponse.FromString,
                )
        self.GetPromocodeComments = channel.unary_unary(
                '/socialnetwork.SocialNetwork/GetPromocodeComments',
                request_serializer=service__pb2.GetPromocodeCommentsRequest.SerializeToString,
                response_deserializer=service__pb2.GetPromocodeCommentsResponse.FromString,
                )


class SocialNetworkServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetPost(self, request, context):
        """Методы для социальной сети
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateComment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetComments(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterClient(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPromocode(self, request, context):
        """Методы для платформы программ лояльности
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClickPromocode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreatePromocodeComment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPromocodeComments(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SocialNetworkServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetPost': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPost,
                    request_deserializer=service__pb2.GetPostRequest.FromString,
                    response_serializer=service__pb2.GetPostResponse.SerializeToString,
            ),
            'CreateComment': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateComment,
                    request_deserializer=service__pb2.CreateCommentRequest.FromString,
                    response_serializer=service__pb2.CreateCommentResponse.SerializeToString,
            ),
            'GetComments': grpc.unary_unary_rpc_method_handler(
                    servicer.GetComments,
                    request_deserializer=service__pb2.GetCommentsRequest.FromString,
                    response_serializer=service__pb2.GetCommentsResponse.SerializeToString,
            ),
            'RegisterClient': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterClient,
                    request_deserializer=service__pb2.RegisterClientRequest.FromString,
                    response_serializer=service__pb2.RegisterClientResponse.SerializeToString,
            ),
            'GetPromocode': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPromocode,
                    request_deserializer=service__pb2.GetPromocodeRequest.FromString,
                    response_serializer=service__pb2.GetPromocodeResponse.SerializeToString,
            ),
            'ClickPromocode': grpc.unary_unary_rpc_method_handler(
                    servicer.ClickPromocode,
                    request_deserializer=service__pb2.ClickPromocodeRequest.FromString,
                    response_serializer=service__pb2.ClickPromocodeResponse.SerializeToString,
            ),
            'CreatePromocodeComment': grpc.unary_unary_rpc_method_handler(
                    servicer.CreatePromocodeComment,
                    request_deserializer=service__pb2.CreatePromocodeCommentRequest.FromString,
                    response_serializer=service__pb2.CreatePromocodeCommentResponse.SerializeToString,
            ),
            'GetPromocodeComments': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPromocodeComments,
                    request_deserializer=service__pb2.GetPromocodeCommentsRequest.FromString,
                    response_serializer=service__pb2.GetPromocodeCommentsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'socialnetwork.SocialNetwork', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SocialNetwork(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetPost(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/socialnetwork.SocialNetwork/GetPost',
            service__pb2.GetPostRequest.SerializeToString,
            service__pb2.GetPostResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateComment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/socialnetwork.SocialNetwork/CreateComment',
            service__pb2.CreateCommentRequest.SerializeToString,
            service__pb2.CreateCommentResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetComments(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/socialnetwork.SocialNetwork/GetComments',
            service__pb2.GetCommentsRequest.SerializeToString,
            service__pb2.GetCommentsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RegisterClient(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/socialnetwork.SocialNetwork/RegisterClient',
            service__pb2.RegisterClientRequest.SerializeToString,
            service__pb2.RegisterClientResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetPromocode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/socialnetwork.SocialNetwork/GetPromocode',
            service__pb2.GetPromocodeRequest.SerializeToString,
            service__pb2.GetPromocodeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ClickPromocode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/socialnetwork.SocialNetwork/ClickPromocode',
            service__pb2.ClickPromocodeRequest.SerializeToString,
            service__pb2.ClickPromocodeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreatePromocodeComment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/socialnetwork.SocialNetwork/CreatePromocodeComment',
            service__pb2.CreatePromocodeCommentRequest.SerializeToString,
            service__pb2.CreatePromocodeCommentResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetPromocodeComments(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/socialnetwork.SocialNetwork/GetPromocodeComments',
            service__pb2.GetPromocodeCommentsRequest.SerializeToString,
            service__pb2.GetPromocodeCommentsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
